### PR TITLE
Update license details

### PR DESCRIPTION
**Pull request by Eonfge**
Upsteam controversy: https://github.com/bitwarden/clients/issues/11611

### CODE REVIEW

**Comment by Eonfge** [comment]
@ghisvail Sadly Bitwarden seems to have gone into a different direction. It's up to us, so that all current and future customers are informed.

**Comment by ghisvail** [comment]
Thanks @Eonfge

This PR would need to be merged after an eventual upgrade to version 2024.10+. The current version packaged by this Flatpak is 2024.9, which is still considered free software, afaik.

Depends-On: #218

**Comment by Eeebru** [comment]
@Eonfge Bitwarden is still commited and fully open source, as you will find out in the next couple of days. The upstream conversation is just a miscontrution that has gannered a lot of traffic.

**Comment by quexten** [comment]
Closing since upstream is GPL compatible again. Still thank you for the PR! 
https://github.com/flathub/com.bitwarden.desktop/issues/219#issuecomment-2449619081

**Pull request closed without merging**
